// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatResponse.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ChatResponse_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ChatResponse_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/timestamp.pb.h>
#include "ChatStatus.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ChatResponse_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ChatResponse_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ChatResponse_2eproto;
class ChatResponse;
class ChatResponseDefaultTypeInternal;
extern ChatResponseDefaultTypeInternal _ChatResponse_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::ChatResponse* Arena::CreateMaybeMessage<::ChatResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class ChatResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ChatResponse) */ {
 public:
  inline ChatResponse() : ChatResponse(nullptr) {};
  virtual ~ChatResponse();

  ChatResponse(const ChatResponse& from);
  ChatResponse(ChatResponse&& from) noexcept
    : ChatResponse() {
    *this = ::std::move(from);
  }

  inline ChatResponse& operator=(const ChatResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ChatResponse& operator=(ChatResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ChatResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ChatResponse* internal_default_instance() {
    return reinterpret_cast<const ChatResponse*>(
               &_ChatResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ChatResponse& a, ChatResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ChatResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ChatResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ChatResponse* New() const final {
    return CreateMaybeMessage<ChatResponse>(nullptr);
  }

  ChatResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ChatResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ChatResponse& from);
  void MergeFrom(const ChatResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ChatResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ChatResponse";
  }
  protected:
  explicit ChatResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ChatResponse_2eproto);
    return ::descriptor_table_ChatResponse_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kConversationFieldNumber = 1,
    kRandomFieldNumber = 2,
    kTimestampFieldNumber = 4,
    kSeqFieldNumber = 3,
    kChatStatusFieldNumber = 5,
  };
  // string conversation = 1;
  void clear_conversation();
  const std::string& conversation() const;
  void set_conversation(const std::string& value);
  void set_conversation(std::string&& value);
  void set_conversation(const char* value);
  void set_conversation(const char* value, size_t size);
  std::string* mutable_conversation();
  std::string* release_conversation();
  void set_allocated_conversation(std::string* conversation);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_conversation();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_conversation(
      std::string* conversation);
  private:
  const std::string& _internal_conversation() const;
  void _internal_set_conversation(const std::string& value);
  std::string* _internal_mutable_conversation();
  public:

  // string random = 2;
  void clear_random();
  const std::string& random() const;
  void set_random(const std::string& value);
  void set_random(std::string&& value);
  void set_random(const char* value);
  void set_random(const char* value, size_t size);
  std::string* mutable_random();
  std::string* release_random();
  void set_allocated_random(std::string* random);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_random();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_random(
      std::string* random);
  private:
  const std::string& _internal_random() const;
  void _internal_set_random(const std::string& value);
  std::string* _internal_mutable_random();
  public:

  // .google.protobuf.Timestamp timestamp = 4;
  bool has_timestamp() const;
  private:
  bool _internal_has_timestamp() const;
  public:
  void clear_timestamp();
  const PROTOBUF_NAMESPACE_ID::Timestamp& timestamp() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* release_timestamp();
  PROTOBUF_NAMESPACE_ID::Timestamp* mutable_timestamp();
  void set_allocated_timestamp(PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  private:
  const PROTOBUF_NAMESPACE_ID::Timestamp& _internal_timestamp() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_timestamp();
  public:
  void unsafe_arena_set_allocated_timestamp(
      PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_timestamp();

  // uint64 seq = 3;
  void clear_seq();
  ::PROTOBUF_NAMESPACE_ID::uint64 seq() const;
  void set_seq(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_seq() const;
  void _internal_set_seq(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // .ChatStatus chatStatus = 5;
  void clear_chatstatus();
  ::ChatStatus chatstatus() const;
  void set_chatstatus(::ChatStatus value);
  private:
  ::ChatStatus _internal_chatstatus() const;
  void _internal_set_chatstatus(::ChatStatus value);
  public:

  // @@protoc_insertion_point(class_scope:ChatResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr conversation_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr random_;
  PROTOBUF_NAMESPACE_ID::Timestamp* timestamp_;
  ::PROTOBUF_NAMESPACE_ID::uint64 seq_;
  int chatstatus_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ChatResponse_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ChatResponse

// string conversation = 1;
inline void ChatResponse::clear_conversation() {
  conversation_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ChatResponse::conversation() const {
  // @@protoc_insertion_point(field_get:ChatResponse.conversation)
  return _internal_conversation();
}
inline void ChatResponse::set_conversation(const std::string& value) {
  _internal_set_conversation(value);
  // @@protoc_insertion_point(field_set:ChatResponse.conversation)
}
inline std::string* ChatResponse::mutable_conversation() {
  // @@protoc_insertion_point(field_mutable:ChatResponse.conversation)
  return _internal_mutable_conversation();
}
inline const std::string& ChatResponse::_internal_conversation() const {
  return conversation_.Get();
}
inline void ChatResponse::_internal_set_conversation(const std::string& value) {
  
  conversation_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ChatResponse::set_conversation(std::string&& value) {
  
  conversation_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:ChatResponse.conversation)
}
inline void ChatResponse::set_conversation(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  conversation_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:ChatResponse.conversation)
}
inline void ChatResponse::set_conversation(const char* value,
    size_t size) {
  
  conversation_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:ChatResponse.conversation)
}
inline std::string* ChatResponse::_internal_mutable_conversation() {
  
  return conversation_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ChatResponse::release_conversation() {
  // @@protoc_insertion_point(field_release:ChatResponse.conversation)
  return conversation_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ChatResponse::set_allocated_conversation(std::string* conversation) {
  if (conversation != nullptr) {
    
  } else {
    
  }
  conversation_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), conversation,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:ChatResponse.conversation)
}
inline std::string* ChatResponse::unsafe_arena_release_conversation() {
  // @@protoc_insertion_point(field_unsafe_arena_release:ChatResponse.conversation)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return conversation_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void ChatResponse::unsafe_arena_set_allocated_conversation(
    std::string* conversation) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (conversation != nullptr) {
    
  } else {
    
  }
  conversation_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      conversation, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ChatResponse.conversation)
}

// string random = 2;
inline void ChatResponse::clear_random() {
  random_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ChatResponse::random() const {
  // @@protoc_insertion_point(field_get:ChatResponse.random)
  return _internal_random();
}
inline void ChatResponse::set_random(const std::string& value) {
  _internal_set_random(value);
  // @@protoc_insertion_point(field_set:ChatResponse.random)
}
inline std::string* ChatResponse::mutable_random() {
  // @@protoc_insertion_point(field_mutable:ChatResponse.random)
  return _internal_mutable_random();
}
inline const std::string& ChatResponse::_internal_random() const {
  return random_.Get();
}
inline void ChatResponse::_internal_set_random(const std::string& value) {
  
  random_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ChatResponse::set_random(std::string&& value) {
  
  random_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:ChatResponse.random)
}
inline void ChatResponse::set_random(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  random_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:ChatResponse.random)
}
inline void ChatResponse::set_random(const char* value,
    size_t size) {
  
  random_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:ChatResponse.random)
}
inline std::string* ChatResponse::_internal_mutable_random() {
  
  return random_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ChatResponse::release_random() {
  // @@protoc_insertion_point(field_release:ChatResponse.random)
  return random_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ChatResponse::set_allocated_random(std::string* random) {
  if (random != nullptr) {
    
  } else {
    
  }
  random_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), random,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:ChatResponse.random)
}
inline std::string* ChatResponse::unsafe_arena_release_random() {
  // @@protoc_insertion_point(field_unsafe_arena_release:ChatResponse.random)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return random_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void ChatResponse::unsafe_arena_set_allocated_random(
    std::string* random) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (random != nullptr) {
    
  } else {
    
  }
  random_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      random, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ChatResponse.random)
}

// uint64 seq = 3;
inline void ChatResponse::clear_seq() {
  seq_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ChatResponse::_internal_seq() const {
  return seq_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ChatResponse::seq() const {
  // @@protoc_insertion_point(field_get:ChatResponse.seq)
  return _internal_seq();
}
inline void ChatResponse::_internal_set_seq(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  seq_ = value;
}
inline void ChatResponse::set_seq(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_seq(value);
  // @@protoc_insertion_point(field_set:ChatResponse.seq)
}

// .google.protobuf.Timestamp timestamp = 4;
inline bool ChatResponse::_internal_has_timestamp() const {
  return this != internal_default_instance() && timestamp_ != nullptr;
}
inline bool ChatResponse::has_timestamp() const {
  return _internal_has_timestamp();
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& ChatResponse::_internal_timestamp() const {
  const PROTOBUF_NAMESPACE_ID::Timestamp* p = timestamp_;
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Timestamp*>(
      &PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& ChatResponse::timestamp() const {
  // @@protoc_insertion_point(field_get:ChatResponse.timestamp)
  return _internal_timestamp();
}
inline void ChatResponse::unsafe_arena_set_allocated_timestamp(
    PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  timestamp_ = timestamp;
  if (timestamp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ChatResponse.timestamp)
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* ChatResponse::release_timestamp() {
  auto temp = unsafe_arena_release_timestamp();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* ChatResponse::unsafe_arena_release_timestamp() {
  // @@protoc_insertion_point(field_release:ChatResponse.timestamp)
  
  PROTOBUF_NAMESPACE_ID::Timestamp* temp = timestamp_;
  timestamp_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* ChatResponse::_internal_mutable_timestamp() {
  
  if (timestamp_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Timestamp>(GetArena());
    timestamp_ = p;
  }
  return timestamp_;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* ChatResponse::mutable_timestamp() {
  // @@protoc_insertion_point(field_mutable:ChatResponse.timestamp)
  return _internal_mutable_timestamp();
}
inline void ChatResponse::set_allocated_timestamp(PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  if (timestamp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp)->GetArena();
    if (message_arena != submessage_arena) {
      timestamp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, timestamp, submessage_arena);
    }
    
  } else {
    
  }
  timestamp_ = timestamp;
  // @@protoc_insertion_point(field_set_allocated:ChatResponse.timestamp)
}

// .ChatStatus chatStatus = 5;
inline void ChatResponse::clear_chatstatus() {
  chatstatus_ = 0;
}
inline ::ChatStatus ChatResponse::_internal_chatstatus() const {
  return static_cast< ::ChatStatus >(chatstatus_);
}
inline ::ChatStatus ChatResponse::chatstatus() const {
  // @@protoc_insertion_point(field_get:ChatResponse.chatStatus)
  return _internal_chatstatus();
}
inline void ChatResponse::_internal_set_chatstatus(::ChatStatus value) {
  
  chatstatus_ = value;
}
inline void ChatResponse::set_chatstatus(::ChatStatus value) {
  _internal_set_chatstatus(value);
  // @@protoc_insertion_point(field_set:ChatResponse.chatStatus)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ChatResponse_2eproto
