// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatStatus.proto

package org.flmelody.wim.message;

/**
 * <pre>
 * 聊天消息响应状态
 * </pre>
 *
 * Protobuf enum {@code ChatStatus}
 */
public enum ChatStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 发送成功
   * </pre>
   *
   * <code>OK = 0;</code>
   */
  OK(0),
  /**
   * <pre>
   * 被禁言
   * </pre>
   *
   * <code>QUIET = 1;</code>
   */
  QUIET(1),
  /**
   * <pre>
   * 被拉黑
   * </pre>
   *
   * <code>BLACK = 2;</code>
   */
  BLACK(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * 发送成功
   * </pre>
   *
   * <code>OK = 0;</code>
   */
  public static final int OK_VALUE = 0;
  /**
   * <pre>
   * 被禁言
   * </pre>
   *
   * <code>QUIET = 1;</code>
   */
  public static final int QUIET_VALUE = 1;
  /**
   * <pre>
   * 被拉黑
   * </pre>
   *
   * <code>BLACK = 2;</code>
   */
  public static final int BLACK_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ChatStatus valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ChatStatus forNumber(int value) {
    switch (value) {
      case 0: return OK;
      case 1: return QUIET;
      case 2: return BLACK;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ChatStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ChatStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ChatStatus>() {
          public ChatStatus findValueByNumber(int number) {
            return ChatStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.flmelody.wim.message.ChatStatusOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final ChatStatus[] VALUES = values();

  public static ChatStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ChatStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ChatStatus)
}

