// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatAck.proto

package org.flmelody.wim.message;

public interface ChatAckOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ChatAck)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 会话id
   * </pre>
   *
   * <code>string conversation = 1;</code>
   * @return The conversation.
   */
  java.lang.String getConversation();
  /**
   * <pre>
   * 会话id
   * </pre>
   *
   * <code>string conversation = 1;</code>
   * @return The bytes for conversation.
   */
  com.google.protobuf.ByteString
      getConversationBytes();

  /**
   * <pre>
   * 消息发送人
   * </pre>
   *
   * <code>string from = 2;</code>
   * @return The from.
   */
  java.lang.String getFrom();
  /**
   * <pre>
   * 消息发送人
   * </pre>
   *
   * <code>string from = 2;</code>
   * @return The bytes for from.
   */
  com.google.protobuf.ByteString
      getFromBytes();

  /**
   * <pre>
   * 收到消息的seq
   * </pre>
   *
   * <code>uint64 seq = 3;</code>
   * @return The seq.
   */
  long getSeq();

  /**
   * <pre>
   * 客户端类型
   * </pre>
   *
   * <code>.ChatClient client = 4;</code>
   * @return The enum numeric value on the wire for client.
   */
  int getClientValue();
  /**
   * <pre>
   * 客户端类型
   * </pre>
   *
   * <code>.ChatClient client = 4;</code>
   * @return The client.
   */
  org.flmelody.wim.message.ChatClient getClient();
}
