// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatResponse.proto

package org.flmelody.wim.message;

public interface ChatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ChatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 会话id
   * </pre>
   *
   * <code>string conversation = 1;</code>
   * @return The conversation.
   */
  java.lang.String getConversation();
  /**
   * <pre>
   * 会话id
   * </pre>
   *
   * <code>string conversation = 1;</code>
   * @return The bytes for conversation.
   */
  com.google.protobuf.ByteString
      getConversationBytes();

  /**
   * <pre>
   * 该会话内消息唯一随机数
   * </pre>
   *
   * <code>string random = 2;</code>
   * @return The random.
   */
  java.lang.String getRandom();
  /**
   * <pre>
   * 该会话内消息唯一随机数
   * </pre>
   *
   * <code>string random = 2;</code>
   * @return The bytes for random.
   */
  com.google.protobuf.ByteString
      getRandomBytes();

  /**
   * <pre>
   * 消息seq
   * </pre>
   *
   * <code>uint64 seq = 3;</code>
   * @return The seq.
   */
  long getSeq();

  /**
   * <pre>
   * 发包时间
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 4;</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <pre>
   * 发包时间
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 4;</code>
   * @return The timestamp.
   */
  com.google.protobuf.Timestamp getTimestamp();
  /**
   * <pre>
   * 发包时间
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();

  /**
   * <pre>
   *消息发送状态
   * </pre>
   *
   * <code>.ChatStatus chatStatus = 5;</code>
   * @return The enum numeric value on the wire for chatStatus.
   */
  int getChatStatusValue();
  /**
   * <pre>
   *消息发送状态
   * </pre>
   *
   * <code>.ChatStatus chatStatus = 5;</code>
   * @return The chatStatus.
   */
  org.flmelody.wim.message.ChatStatus getChatStatus();
}
