// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatMessage.proto

package org.flmelody.wim.message;

public interface ChatMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ChatMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 会话id
   * </pre>
   *
   * <code>string conversation = 1;</code>
   * @return The conversation.
   */
  java.lang.String getConversation();
  /**
   * <pre>
   * 会话id
   * </pre>
   *
   * <code>string conversation = 1;</code>
   * @return The bytes for conversation.
   */
  com.google.protobuf.ByteString
      getConversationBytes();

  /**
   * <pre>
   * 该会话内消息唯一随机数
   * </pre>
   *
   * <code>string random = 2;</code>
   * @return The random.
   */
  java.lang.String getRandom();
  /**
   * <pre>
   * 该会话内消息唯一随机数
   * </pre>
   *
   * <code>string random = 2;</code>
   * @return The bytes for random.
   */
  com.google.protobuf.ByteString
      getRandomBytes();

  /**
   * <pre>
   * 该消息seq,客户端无需设置,回发消息有返回
   * </pre>
   *
   * <code>uint64 seq = 3;</code>
   * @return The seq.
   */
  long getSeq();

  /**
   * <pre>
   *发送人
   * </pre>
   *
   * <code>string from = 4;</code>
   * @return The from.
   */
  java.lang.String getFrom();
  /**
   * <pre>
   *发送人
   * </pre>
   *
   * <code>string from = 4;</code>
   * @return The bytes for from.
   */
  com.google.protobuf.ByteString
      getFromBytes();

  /**
   * <pre>
   * 接收人
   * </pre>
   *
   * <code>string to = 5;</code>
   * @return The to.
   */
  java.lang.String getTo();
  /**
   * <pre>
   * 接收人
   * </pre>
   *
   * <code>string to = 5;</code>
   * @return The bytes for to.
   */
  com.google.protobuf.ByteString
      getToBytes();

  /**
   * <pre>
   * 消息体
   * </pre>
   *
   * <code>string content = 6;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <pre>
   * 消息体
   * </pre>
   *
   * <code>string content = 6;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <pre>
   * 消息是否被撤回  当存在同一seq时需比对最新收到的是否为撤回消息
   * </pre>
   *
   * <code>bool withdraw = 7;</code>
   * @return The withdraw.
   */
  boolean getWithdraw();

  /**
   * <pre>
   * 发包时间
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 8;</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <pre>
   * 发包时间
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 8;</code>
   * @return The timestamp.
   */
  com.google.protobuf.Timestamp getTimestamp();
  /**
   * <pre>
   * 发包时间
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 8;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();

  /**
   * <pre>
   * 客户端类型
   * </pre>
   *
   * <code>.ChatClient client = 9;</code>
   * @return The enum numeric value on the wire for client.
   */
  int getClientValue();
  /**
   * <pre>
   * 客户端类型
   * </pre>
   *
   * <code>.ChatClient client = 9;</code>
   * @return The client.
   */
  org.flmelody.wim.message.ChatClient getClient();
}
