// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatMessage.proto

package org.flmelody.wim.message;

public final class ChatMessageOuterClass {
  private ChatMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChatMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChatMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ChatMessage.proto\032\037google/protobuf/tim" +
      "estamp.proto\032\020ChatClient.proto\032\016ChatType" +
      ".proto\"\342\001\n\013ChatMessage\022\024\n\014conversation\030\001" +
      " \001(\t\022\016\n\006random\030\002 \001(\t\022\013\n\003seq\030\003 \001(\004\022\014\n\004fro" +
      "m\030\004 \001(\t\022\n\n\002to\030\005 \001(\t\022\017\n\007content\030\006 \001(\t\022\020\n\010" +
      "withdraw\030\007 \001(\010\022-\n\ttimestamp\030\010 \001(\0132\032.goog" +
      "le.protobuf.Timestamp\022\033\n\006client\030\t \001(\0162\013." +
      "ChatClient\022\027\n\004type\030\n \001(\0162\t.ChatTypeB\034\n\030o" +
      "rg.flmelody.wim.messageP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          org.flmelody.wim.message.ChatClientOuterClass.getDescriptor(),
          org.flmelody.wim.message.ChatTypeOuterClass.getDescriptor(),
        });
    internal_static_ChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChatMessage_descriptor,
        new java.lang.String[] { "Conversation", "Random", "Seq", "From", "To", "Content", "Withdraw", "Timestamp", "Client", "Type", });
    com.google.protobuf.TimestampProto.getDescriptor();
    org.flmelody.wim.message.ChatClientOuterClass.getDescriptor();
    org.flmelody.wim.message.ChatTypeOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
