// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatResponse.proto

package org.flmelody.wim.message;

/**
 * <pre>
 * 聊天响应
 * </pre>
 *
 * Protobuf type {@code ChatResponse}
 */
public final class ChatResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ChatResponse)
    ChatResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ChatResponse.newBuilder() to construct.
  private ChatResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ChatResponse() {
    conversation_ = "";
    random_ = "";
    chatStatus_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ChatResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ChatResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            conversation_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            random_ = s;
            break;
          }
          case 24: {

            seq_ = input.readUInt64();
            break;
          }
          case 34: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (timestamp_ != null) {
              subBuilder = timestamp_.toBuilder();
            }
            timestamp_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(timestamp_);
              timestamp_ = subBuilder.buildPartial();
            }

            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            chatStatus_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.flmelody.wim.message.ChatResponseOuterClass.internal_static_ChatResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.flmelody.wim.message.ChatResponseOuterClass.internal_static_ChatResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.flmelody.wim.message.ChatResponse.class, org.flmelody.wim.message.ChatResponse.Builder.class);
  }

  public static final int CONVERSATION_FIELD_NUMBER = 1;
  private volatile java.lang.Object conversation_;
  /**
   * <pre>
   * 会话id
   * </pre>
   *
   * <code>string conversation = 1;</code>
   * @return The conversation.
   */
  @java.lang.Override
  public java.lang.String getConversation() {
    java.lang.Object ref = conversation_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      conversation_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 会话id
   * </pre>
   *
   * <code>string conversation = 1;</code>
   * @return The bytes for conversation.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getConversationBytes() {
    java.lang.Object ref = conversation_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      conversation_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RANDOM_FIELD_NUMBER = 2;
  private volatile java.lang.Object random_;
  /**
   * <pre>
   * 该会话内消息唯一随机数
   * </pre>
   *
   * <code>string random = 2;</code>
   * @return The random.
   */
  @java.lang.Override
  public java.lang.String getRandom() {
    java.lang.Object ref = random_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      random_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 该会话内消息唯一随机数
   * </pre>
   *
   * <code>string random = 2;</code>
   * @return The bytes for random.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRandomBytes() {
    java.lang.Object ref = random_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      random_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEQ_FIELD_NUMBER = 3;
  private long seq_;
  /**
   * <pre>
   * 消息seq
   * </pre>
   *
   * <code>uint64 seq = 3;</code>
   * @return The seq.
   */
  @java.lang.Override
  public long getSeq() {
    return seq_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 4;
  private com.google.protobuf.Timestamp timestamp_;
  /**
   * <pre>
   * 发包时间
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 4;</code>
   * @return Whether the timestamp field is set.
   */
  @java.lang.Override
  public boolean hasTimestamp() {
    return timestamp_ != null;
  }
  /**
   * <pre>
   * 发包时间
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 4;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getTimestamp() {
    return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
  }
  /**
   * <pre>
   * 发包时间
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
    return getTimestamp();
  }

  public static final int CHATSTATUS_FIELD_NUMBER = 5;
  private int chatStatus_;
  /**
   * <pre>
   *消息发送状态
   * </pre>
   *
   * <code>.ChatStatus chatStatus = 5;</code>
   * @return The enum numeric value on the wire for chatStatus.
   */
  @java.lang.Override public int getChatStatusValue() {
    return chatStatus_;
  }
  /**
   * <pre>
   *消息发送状态
   * </pre>
   *
   * <code>.ChatStatus chatStatus = 5;</code>
   * @return The chatStatus.
   */
  @java.lang.Override public org.flmelody.wim.message.ChatStatus getChatStatus() {
    @SuppressWarnings("deprecation")
    org.flmelody.wim.message.ChatStatus result = org.flmelody.wim.message.ChatStatus.valueOf(chatStatus_);
    return result == null ? org.flmelody.wim.message.ChatStatus.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getConversationBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, conversation_);
    }
    if (!getRandomBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, random_);
    }
    if (seq_ != 0L) {
      output.writeUInt64(3, seq_);
    }
    if (timestamp_ != null) {
      output.writeMessage(4, getTimestamp());
    }
    if (chatStatus_ != org.flmelody.wim.message.ChatStatus.OK.getNumber()) {
      output.writeEnum(5, chatStatus_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getConversationBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, conversation_);
    }
    if (!getRandomBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, random_);
    }
    if (seq_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, seq_);
    }
    if (timestamp_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getTimestamp());
    }
    if (chatStatus_ != org.flmelody.wim.message.ChatStatus.OK.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, chatStatus_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.flmelody.wim.message.ChatResponse)) {
      return super.equals(obj);
    }
    org.flmelody.wim.message.ChatResponse other = (org.flmelody.wim.message.ChatResponse) obj;

    if (!getConversation()
        .equals(other.getConversation())) return false;
    if (!getRandom()
        .equals(other.getRandom())) return false;
    if (getSeq()
        != other.getSeq()) return false;
    if (hasTimestamp() != other.hasTimestamp()) return false;
    if (hasTimestamp()) {
      if (!getTimestamp()
          .equals(other.getTimestamp())) return false;
    }
    if (chatStatus_ != other.chatStatus_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONVERSATION_FIELD_NUMBER;
    hash = (53 * hash) + getConversation().hashCode();
    hash = (37 * hash) + RANDOM_FIELD_NUMBER;
    hash = (53 * hash) + getRandom().hashCode();
    hash = (37 * hash) + SEQ_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSeq());
    if (hasTimestamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
    }
    hash = (37 * hash) + CHATSTATUS_FIELD_NUMBER;
    hash = (53 * hash) + chatStatus_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.flmelody.wim.message.ChatResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.flmelody.wim.message.ChatResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.flmelody.wim.message.ChatResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.flmelody.wim.message.ChatResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.flmelody.wim.message.ChatResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.flmelody.wim.message.ChatResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.flmelody.wim.message.ChatResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.flmelody.wim.message.ChatResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.flmelody.wim.message.ChatResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.flmelody.wim.message.ChatResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.flmelody.wim.message.ChatResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.flmelody.wim.message.ChatResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.flmelody.wim.message.ChatResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 聊天响应
   * </pre>
   *
   * Protobuf type {@code ChatResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ChatResponse)
      org.flmelody.wim.message.ChatResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.flmelody.wim.message.ChatResponseOuterClass.internal_static_ChatResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.flmelody.wim.message.ChatResponseOuterClass.internal_static_ChatResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.flmelody.wim.message.ChatResponse.class, org.flmelody.wim.message.ChatResponse.Builder.class);
    }

    // Construct using org.flmelody.wim.message.ChatResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      conversation_ = "";

      random_ = "";

      seq_ = 0L;

      if (timestampBuilder_ == null) {
        timestamp_ = null;
      } else {
        timestamp_ = null;
        timestampBuilder_ = null;
      }
      chatStatus_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.flmelody.wim.message.ChatResponseOuterClass.internal_static_ChatResponse_descriptor;
    }

    @java.lang.Override
    public org.flmelody.wim.message.ChatResponse getDefaultInstanceForType() {
      return org.flmelody.wim.message.ChatResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.flmelody.wim.message.ChatResponse build() {
      org.flmelody.wim.message.ChatResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.flmelody.wim.message.ChatResponse buildPartial() {
      org.flmelody.wim.message.ChatResponse result = new org.flmelody.wim.message.ChatResponse(this);
      result.conversation_ = conversation_;
      result.random_ = random_;
      result.seq_ = seq_;
      if (timestampBuilder_ == null) {
        result.timestamp_ = timestamp_;
      } else {
        result.timestamp_ = timestampBuilder_.build();
      }
      result.chatStatus_ = chatStatus_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.flmelody.wim.message.ChatResponse) {
        return mergeFrom((org.flmelody.wim.message.ChatResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.flmelody.wim.message.ChatResponse other) {
      if (other == org.flmelody.wim.message.ChatResponse.getDefaultInstance()) return this;
      if (!other.getConversation().isEmpty()) {
        conversation_ = other.conversation_;
        onChanged();
      }
      if (!other.getRandom().isEmpty()) {
        random_ = other.random_;
        onChanged();
      }
      if (other.getSeq() != 0L) {
        setSeq(other.getSeq());
      }
      if (other.hasTimestamp()) {
        mergeTimestamp(other.getTimestamp());
      }
      if (other.chatStatus_ != 0) {
        setChatStatusValue(other.getChatStatusValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.flmelody.wim.message.ChatResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.flmelody.wim.message.ChatResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object conversation_ = "";
    /**
     * <pre>
     * 会话id
     * </pre>
     *
     * <code>string conversation = 1;</code>
     * @return The conversation.
     */
    public java.lang.String getConversation() {
      java.lang.Object ref = conversation_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        conversation_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 会话id
     * </pre>
     *
     * <code>string conversation = 1;</code>
     * @return The bytes for conversation.
     */
    public com.google.protobuf.ByteString
        getConversationBytes() {
      java.lang.Object ref = conversation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        conversation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 会话id
     * </pre>
     *
     * <code>string conversation = 1;</code>
     * @param value The conversation to set.
     * @return This builder for chaining.
     */
    public Builder setConversation(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      conversation_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 会话id
     * </pre>
     *
     * <code>string conversation = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearConversation() {
      
      conversation_ = getDefaultInstance().getConversation();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 会话id
     * </pre>
     *
     * <code>string conversation = 1;</code>
     * @param value The bytes for conversation to set.
     * @return This builder for chaining.
     */
    public Builder setConversationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      conversation_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object random_ = "";
    /**
     * <pre>
     * 该会话内消息唯一随机数
     * </pre>
     *
     * <code>string random = 2;</code>
     * @return The random.
     */
    public java.lang.String getRandom() {
      java.lang.Object ref = random_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        random_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 该会话内消息唯一随机数
     * </pre>
     *
     * <code>string random = 2;</code>
     * @return The bytes for random.
     */
    public com.google.protobuf.ByteString
        getRandomBytes() {
      java.lang.Object ref = random_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        random_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 该会话内消息唯一随机数
     * </pre>
     *
     * <code>string random = 2;</code>
     * @param value The random to set.
     * @return This builder for chaining.
     */
    public Builder setRandom(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      random_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 该会话内消息唯一随机数
     * </pre>
     *
     * <code>string random = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRandom() {
      
      random_ = getDefaultInstance().getRandom();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 该会话内消息唯一随机数
     * </pre>
     *
     * <code>string random = 2;</code>
     * @param value The bytes for random to set.
     * @return This builder for chaining.
     */
    public Builder setRandomBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      random_ = value;
      onChanged();
      return this;
    }

    private long seq_ ;
    /**
     * <pre>
     * 消息seq
     * </pre>
     *
     * <code>uint64 seq = 3;</code>
     * @return The seq.
     */
    @java.lang.Override
    public long getSeq() {
      return seq_;
    }
    /**
     * <pre>
     * 消息seq
     * </pre>
     *
     * <code>uint64 seq = 3;</code>
     * @param value The seq to set.
     * @return This builder for chaining.
     */
    public Builder setSeq(long value) {
      
      seq_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息seq
     * </pre>
     *
     * <code>uint64 seq = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeq() {
      
      seq_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp timestamp_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
    /**
     * <pre>
     * 发包时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 4;</code>
     * @return Whether the timestamp field is set.
     */
    public boolean hasTimestamp() {
      return timestampBuilder_ != null || timestamp_ != null;
    }
    /**
     * <pre>
     * 发包时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 4;</code>
     * @return The timestamp.
     */
    public com.google.protobuf.Timestamp getTimestamp() {
      if (timestampBuilder_ == null) {
        return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      } else {
        return timestampBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 发包时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 4;</code>
     */
    public Builder setTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timestamp_ = value;
        onChanged();
      } else {
        timestampBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 发包时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 4;</code>
     */
    public Builder setTimestamp(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timestampBuilder_ == null) {
        timestamp_ = builderForValue.build();
        onChanged();
      } else {
        timestampBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 发包时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 4;</code>
     */
    public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (timestamp_ != null) {
          timestamp_ =
            com.google.protobuf.Timestamp.newBuilder(timestamp_).mergeFrom(value).buildPartial();
        } else {
          timestamp_ = value;
        }
        onChanged();
      } else {
        timestampBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 发包时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 4;</code>
     */
    public Builder clearTimestamp() {
      if (timestampBuilder_ == null) {
        timestamp_ = null;
        onChanged();
      } else {
        timestamp_ = null;
        timestampBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 发包时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 4;</code>
     */
    public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
      
      onChanged();
      return getTimestampFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 发包时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      if (timestampBuilder_ != null) {
        return timestampBuilder_.getMessageOrBuilder();
      } else {
        return timestamp_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      }
    }
    /**
     * <pre>
     * 发包时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getTimestampFieldBuilder() {
      if (timestampBuilder_ == null) {
        timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getTimestamp(),
                getParentForChildren(),
                isClean());
        timestamp_ = null;
      }
      return timestampBuilder_;
    }

    private int chatStatus_ = 0;
    /**
     * <pre>
     *消息发送状态
     * </pre>
     *
     * <code>.ChatStatus chatStatus = 5;</code>
     * @return The enum numeric value on the wire for chatStatus.
     */
    @java.lang.Override public int getChatStatusValue() {
      return chatStatus_;
    }
    /**
     * <pre>
     *消息发送状态
     * </pre>
     *
     * <code>.ChatStatus chatStatus = 5;</code>
     * @param value The enum numeric value on the wire for chatStatus to set.
     * @return This builder for chaining.
     */
    public Builder setChatStatusValue(int value) {
      
      chatStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *消息发送状态
     * </pre>
     *
     * <code>.ChatStatus chatStatus = 5;</code>
     * @return The chatStatus.
     */
    @java.lang.Override
    public org.flmelody.wim.message.ChatStatus getChatStatus() {
      @SuppressWarnings("deprecation")
      org.flmelody.wim.message.ChatStatus result = org.flmelody.wim.message.ChatStatus.valueOf(chatStatus_);
      return result == null ? org.flmelody.wim.message.ChatStatus.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *消息发送状态
     * </pre>
     *
     * <code>.ChatStatus chatStatus = 5;</code>
     * @param value The chatStatus to set.
     * @return This builder for chaining.
     */
    public Builder setChatStatus(org.flmelody.wim.message.ChatStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      chatStatus_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *消息发送状态
     * </pre>
     *
     * <code>.ChatStatus chatStatus = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearChatStatus() {
      
      chatStatus_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ChatResponse)
  }

  // @@protoc_insertion_point(class_scope:ChatResponse)
  private static final org.flmelody.wim.message.ChatResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.flmelody.wim.message.ChatResponse();
  }

  public static org.flmelody.wim.message.ChatResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChatResponse>
      PARSER = new com.google.protobuf.AbstractParser<ChatResponse>() {
    @java.lang.Override
    public ChatResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ChatResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ChatResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChatResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.flmelody.wim.message.ChatResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

