// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatClient.proto

package org.flmelody.wim.message;

public final class ChatClientOuterClass {
  private ChatClientOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020ChatClient.proto*<\n\nChatClient\022\013\n\007UNKN" +
      "OWN\020\000\022\n\n\006MOBILE\020\001\022\013\n\007DESKTOP\020\002\022\010\n\004IPAD\020\003" +
      "B\034\n\030org.flmelody.wim.messageP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
