// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatAck.proto

package org.flmelody.wim.message;

public final class ChatAckOuterClass {
  private ChatAckOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChatAck_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChatAck_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rChatAck.proto\032\020ChatClient.proto\"W\n\007Cha" +
      "tAck\022\024\n\014conversation\030\001 \001(\t\022\014\n\004from\030\002 \001(\t" +
      "\022\013\n\003seq\030\003 \001(\004\022\033\n\006client\030\004 \001(\0162\013.ChatClie" +
      "ntB\034\n\030org.flmelody.wim.messageP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.flmelody.wim.message.ChatClientOuterClass.getDescriptor(),
        });
    internal_static_ChatAck_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ChatAck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChatAck_descriptor,
        new java.lang.String[] { "Conversation", "From", "Seq", "Client", });
    org.flmelody.wim.message.ChatClientOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
