// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatClient.proto

package org.flmelody.wim.message;

/**
 * <pre>
 * 客户端类型
 * </pre>
 *
 * Protobuf enum {@code ChatClient}
 */
public enum ChatClient
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN = 0;</code>
   */
  UNKNOWN(0),
  /**
   * <pre>
   * 手机端
   * </pre>
   *
   * <code>MOBILE = 1;</code>
   */
  MOBILE(1),
  /**
   * <pre>
   * 桌面端
   * </pre>
   *
   * <code>DESKTOP = 2;</code>
   */
  DESKTOP(2),
  /**
   * <pre>
   * IPAD端
   * </pre>
   *
   * <code>IPAD = 3;</code>
   */
  IPAD(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNKNOWN = 0;</code>
   */
  public static final int UNKNOWN_VALUE = 0;
  /**
   * <pre>
   * 手机端
   * </pre>
   *
   * <code>MOBILE = 1;</code>
   */
  public static final int MOBILE_VALUE = 1;
  /**
   * <pre>
   * 桌面端
   * </pre>
   *
   * <code>DESKTOP = 2;</code>
   */
  public static final int DESKTOP_VALUE = 2;
  /**
   * <pre>
   * IPAD端
   * </pre>
   *
   * <code>IPAD = 3;</code>
   */
  public static final int IPAD_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ChatClient valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ChatClient forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN;
      case 1: return MOBILE;
      case 2: return DESKTOP;
      case 3: return IPAD;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ChatClient>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ChatClient> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ChatClient>() {
          public ChatClient findValueByNumber(int number) {
            return ChatClient.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.flmelody.wim.message.ChatClientOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final ChatClient[] VALUES = values();

  public static ChatClient valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ChatClient(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ChatClient)
}

