// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatStatus.proto

package org.flmelody.wim.message;

public final class ChatStatusOuterClass {
  private ChatStatusOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020ChatStatus.proto**\n\nChatStatus\022\006\n\002OK\020\000" +
      "\022\t\n\005QUIET\020\001\022\t\n\005BLACK\020\002B\034\n\030org.flmelody.w" +
      "im.messageP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
