// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FriendAdd.proto

package org.flmelody.wim.message;

public final class FriendAddOuterClass {
  private FriendAddOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FriendAdd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FriendAdd_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017FriendAdd.proto\032\037google/protobuf/times" +
      "tamp.proto\"T\n\tFriendAdd\022\014\n\004from\030\001 \001(\t\022\n\n" +
      "\002to\030\002 \001(\t\022-\n\ttimestamp\030\003 \001(\0132\032.google.pr" +
      "otobuf.TimestampB\034\n\030org.flmelody.wim.mes" +
      "sageP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_FriendAdd_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FriendAdd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FriendAdd_descriptor,
        new java.lang.String[] { "From", "To", "Timestamp", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
