// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Heartbeat.proto

package org.flmelody.wim.message;

public interface HeartbeatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Heartbeat)
    com.google.protobuf.MessageOrBuilder {
}
